# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Instructions_Pop_up.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(0, 0, 801, 591))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.textBrowser.setFont(font)
        self.textBrowser.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textBrowser.setStyleSheet("background-color: rgb(26, 62, 88)")
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                            "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                            "p, li { white-space: pre-wrap; }\n"
                                            "</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:20pt; font-weight:400; font-style:normal;\">\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8.25pt; font-weight:600;\"> </span><span style=\" font-weight:600;\">Instructions </span></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">On opening the UI you can start the pi_image_send to send the image  </span></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">Once the Image is sent, the UI will update when the Image and text are ready</span></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt;\">When the images show, the text can be controlled with voice or pose control or the keyboard short cuts</span></p>\n"
                                            "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:18pt;\"><br /></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">Buttons: </span></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%; background-color:transparent;\"><a name=\"docs-internal-guid-1b784d81-7fff-6917-0ffc-9d605d237daf\"></a><span style=\" font-family:\'Arial\'; font-size:16pt; color:#000000; background-color:transparent;\">L</span><span style=\" font-family:\'Arial\'; font-size:16pt; color:#000000; background-color:transparent;\">oad Image: where the user can preload an image in</span></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%; background-color:transparent;\"><span style=\" font-family:\'Arial\'; font-size:16pt; color:#000000; background-color:transparent;\">Run: run the OCR on the image in the image box</span></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%; background-color:transparent;\"><span style=\" font-family:\'Arial\'; font-size:16pt; color:#000000; background-color:transparent;\">Clear: clears any text in the text box</span></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%; background-color:transparent;\"><span style=\" font-family:\'Arial\'; font-size:16pt; color:#000000; background-color:transparent;\">Save text: save the text in the textbox</span></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%; background-color:transparent;\"><span style=\" font-family:\'Arial\'; font-size:16pt; color:#000000; background-color:transparent;\">Save Image: save the image in the image box</span></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%; background-color:transparent;\"><span style=\" font-family:\'Arial\'; font-size:16pt; color:#000000; background-color:transparent;\">Mic: used to turn on and off the speech recognition</span></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%; background-color:transparent;\"><span style=\" font-family:\'Arial\'; font-size:16pt; color:#000000; background-color:transparent;\">Hand: used to turn on and off the gesture control</span></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%; background-color:transparent;\"><span style=\" font-family:\'Arial\'; font-size:16pt; color:#000000; background-color:transparent;\">Start/Stop for the text reading</span></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%; background-color:transparent;\"><span style=\" font-family:\'Arial\'; font-size:16pt; color:#000000; background-color:transparent;\">Volume up/Volume down</span></p>\n"
                                            "<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%; font-family:\'Arial\'; font-size:18pt; color:#000000; background-color:transparent;\"><br /></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600;\">KeyBoard Short cuts: </span></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%; background-color:transparent;\"><a name=\"docs-internal-guid-fcdaf46b-7fff-8481-8066-0ae15f5ace32\"></a><span style=\" font-family:\'Comfortaa\',\'cursive\'; font-size:14pt; color:#000000; background-color:transparent;\">Q</span><span style=\" font-family:\'Comfortaa\',\'cursive\'; font-size:14pt; color:#000000; background-color:transparent;\">: play</span></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%; background-color:transparent;\"><span style=\" font-family:\'Comfortaa\',\'cursive\'; font-size:14pt; color:#000000; background-color:transparent;\">W: pause</span></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%; background-color:transparent;\"><span style=\" font-family:\'Comfortaa\',\'cursive\'; font-size:14pt; color:#000000; background-color:transparent;\">E: stop</span></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%; background-color:transparent;\"><span style=\" font-family:\'Comfortaa\',\'cursive\'; font-size:14pt; color:#000000; background-color:transparent;\">A: toggle speech recognition</span></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%; background-color:transparent;\"><span style=\" font-family:\'Comfortaa\',\'cursive\'; font-size:14pt; color:#000000; background-color:transparent;\">S: toggle pose recognition</span></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%; background-color:transparent;\"><span style=\" font-family:\'Comfortaa\',\'cursive\'; font-size:14pt; color:#000000; background-color:transparent;\">Z: load image</span></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%; background-color:transparent;\"><span style=\" font-family:\'Comfortaa\',\'cursive\'; font-size:14pt; color:#000000; background-color:transparent;\">X: clear text from textbox</span></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%; background-color:transparent;\"><span style=\" font-family:\'Comfortaa\',\'cursive\'; font-size:14pt; color:#000000; background-color:transparent;\">C: save text</span></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%; background-color:transparent;\"><span style=\" font-family:\'Comfortaa\',\'cursive\'; font-size:14pt; color:#000000; background-color:transparent;\">V: save image</span></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%; background-color:transparent;\"><span style=\" font-family:\'Comfortaa\',\'cursive\'; font-size:14pt; color:#000000; background-color:transparent;\">Escape: Instructions</span></p>\n"
                                            "<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; line-height:138%; background-color:transparent;\"><span style=\" font-family:\'Comfortaa\',\'cursive\'; font-size:14pt; color:#000000; background-color:transparent;\">Space: Run</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
