# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os
import re
import cv2
import pytesseract
#from StartPage import Ui_MainWindow2
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon, QPixmap


def closeIt():
    exit()


class Ui_MainWindow(object):
    def __init__(self):
        pytesseract.pytesseract.tesseract_cmd = r'C:\Program Files\Tesseract-OCR\tesseract.exe'

    # def openWindow(self):
    #     self.window = QtWidgets.QMainWindow()
    #     self.ui = Ui_MainWindow2()
    #     self.ui.setupUi(self.window)
    #     self.window.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(3000, 3000)
        MainWindow.setStyleSheet("QMainWindow#MainWindow\n"
                                 "{\n"
                                 "    background-color:rgb(100,100,100);\n"
                                 "    /*background-image: url(\'H:/Github/PythonScripts/PyQtDesigner/WebScrapper/bg.png\');*/\n"
                                 "     background-position: center; /* Center the image */\n"
                                 "    background-repeat: no-repeat;\n"
                                 "}\n"
                                 "\n"
                                 "\n"
                                 "\n"
                                 "QLabel\n"
                                 "{    \n"
                                 "    background-color:rgb(255,255,255);\n"
                                 "}\n"
                                 "\n"
                                 "QPushButton\n"
                                 "{\n"
                                 "    border-color: black;\n"
                                 "      border-width: 1px 1px 1px 1px;\n"
                                 "\n"
                                 "}\n"
                                 "\n"
                                 "\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonGetImage = QtWidgets.QPushButton(self.centralwidget)
        self.buttonGetImage.setGeometry(QtCore.QRect(30, 610, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonGetImage.setFont(font)
        self.buttonGetImage.setObjectName("buttonGetImage")
        self.labelImage = QtWidgets.QLabel(self.centralwidget)
        self.labelImage.setGeometry(QtCore.QRect(30, 50, 711, 470))
        self.labelImage.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.labelImage.setText("")
        self.labelImage.setObjectName("labelImage")
        self.labelImage.setScaledContents(True)
        self.buttonExtractText = QtWidgets.QPushButton(self.centralwidget)
        self.buttonExtractText.setGeometry(QtCore.QRect(30, 660, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonExtractText.setFont(font)
        self.buttonExtractText.setObjectName("buttonExtractText")
        self.buttonClear = QtWidgets.QPushButton(self.centralwidget)
        self.buttonClear.setGeometry(QtCore.QRect(30, 710, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonClear.setFont(font)
        self.buttonClear.setObjectName("buttonClear")
        self.buttonSave = QtWidgets.QPushButton(self.centralwidget)
        self.buttonSave.setGeometry(QtCore.QRect(30, 760, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonSave.setFont(font)
        self.buttonSave.setObjectName("buttonSave")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(1000, 50, 711, 470))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.textEdit.setFont(font)
        self.textEdit.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.textEdit.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEdit.setObjectName("textEdit")

       # TO DO
        # helpful source to do this: https://www.youtube.com/watch?v=82v2ZR-g6wY&ab_channel=CodeFirstwithHala
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 860, 171, 41))
        self.pushButton_3.setObjectName("pushButton_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 910, 171, 41))
        self.pushButton_4.setObjectName("pushButton_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 810, 171, 41))
        self.pushButton_5.setObjectName("pushButton_3")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1158, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.buttonGetImage.clicked.connect(self.getImage)
        self.buttonExtractText.clicked.connect(self.extractText)
        self.buttonExtractText.setEnabled(False)
        self.buttonClear.clicked.connect(self.clearText)
        self.buttonSave.clicked.connect(self.saveText)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "README"))
        scriptDir = os.path.dirname(os.path.realpath(__file__))
        MainWindow.setWindowIcon(QtGui.QIcon(
            scriptDir + os.path.sep + 'ocrLogo.png'))
        self.buttonGetImage.setText(_translate("MainWindow", "Load image"))
        self.buttonExtractText.setText(_translate("MainWindow", "Run"))
        self.buttonClear.setText(_translate("MainWindow", "Clear"))
        self.buttonSave.setText(_translate("MainWindow", "Save text"))
        # TO DO
        self.pushButton_3.setText(_translate("MainWindow", "Instructions"))
      #  self.pushButton_3.clicked.connect(self.openWindow)
        self.pushButton_4.setText(_translate("MainWindow", "Exit"))
        self.pushButton_4.clicked.connect(closeIt)
        self.pushButton_5.setText(_translate("MainWindow", "Options"))

    def getImage(self):
        options = QtWidgets.QFileDialog.Options()
        options |= QtWidgets.QFileDialog.DontUseNativeDialog
        self.fileName, _ = QtWidgets.QFileDialog.getOpenFileName(
            options=options)
        # self.fileName, _ = QtWidgets.QFileDialog.getOpenFileName(self,"Open a image", "","All Files (*);;Image Files (*.jpg);;Image Files (*.png)", options=options)
        if self.fileName:
            print(self.fileName)
            pattern = ".(jpg|png|jpeg|bmp|jpe|tiff)$"
            if re.search(pattern, self.fileName):
                self.setImage(self.fileName)

    def setImage(self, fileName):
        self.labelImage.setPixmap(QPixmap(fileName))
        self.buttonExtractText.setEnabled(True)

    def extractText(self):
        config = ('-l eng --oem 1 --psm 3')
        img = cv2.imread(self.fileName, cv2.IMREAD_COLOR)
        # Run tesseract OCR on image
        text = pytesseract.image_to_string(img, config=config)
        # Print recognized text
        self.textEdit.append(text)
        print(text)

    def clearText(self):
        self.textEdit.clear()

    def saveText(self):
        options = QtWidgets.QFileDialog.Options()
        options |= QtWidgets.QFileDialog.DontUseNativeDialog
        # fileName, _ = QtWidgets.QFileDialog.getSaveFileName(self,"Save text","All Files (*);;Text Files (*.txt)", options=options)
        fileName, _ = QtWidgets.QFileDialog.getSaveFileName(options=options)
        if fileName:
            print(fileName)
            file = open(fileName, 'w')
            text = self.textEdit.toPlainText()
            file.write(text)
            file.close()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
